### ISSUE TITLE
Get it to work with a named package

### ISSUE THREAD

**Issue by ddennis** [Aaron-Ritter/example-app-release-please#87]
Thank you for sharing this repo.
I found your repo from [this thread ](https://github.com/googleapis/release-please/issues/2515) trying to debug the same issues.

When I try your setup with only a root "." package - everything works.

In my case I have two packages in the same repo named **frontend** and a **backend**.
[the repo is here](https://github.com/ddennis/release-please-prerelease-example/tree/main/.github). I only added the "frontend" for simplicity.

I have the following issues:
1. the prerelease-config.json goes out of sync after a release. When v2.0.0 is released - the next RC is 1.9.0-rc.1
2. When a release is published a new PR is automatically opened

The solution to 1. was to manually update the version in the **prerelease-manifest.json**
This solution is [show in this repo ](https://github.com/3sidedcube/example-app/blob/main/.github/workflows/release.yaml#L79-L93) - i think it was you linked to it somewhere.

**Any help would be greatly appreciated.**
I know some of these issues are also mentioned on in the release-please repo. But maybe you knew of a simple fix.

My configs:
> prerelease-config.json
``` 
{
  "release-type": "simple",
  "prerelease": true,
  "prerelease-type": "rc",
  "versioning": "prerelease",
  "changelog-sections": [
    ...
  ],
  "packages": {    
    "frontend": {
      "type": "generic",
      "version-file": "version.txt"
    }
  }
}
```

> release-config.json
``` 
{
  "release-type": "simple",
  "changelog-sections": [
      ... 
 ],
  "packages": {    
    "frontend":{
      "type": "generic",
      "version-file": "version.txt",
      "extra-files": [ 
         {
          "type": "json",
          "path": "..\\/.github/prerelease-manifest.json",          
          "jsonpath": "$[\"frontend\"]"
        },              
        {
          "type": "json",
          "path": "package.json",
          "jsonpath": "$.version"
        }               
      ]
    }
  } 
}
```

> release-config.json and prerelease-config.json
```
{
  "frontend":  "1.30.0"
}
```

I have also updated the **tag_name** to read from the nested package:

```
tag_name: ${{ ( contains(steps.release.outputs.frontend--tag_name, 'rc') || contains(steps.release.outputs.backend--tag_name, 'rc')) && 'rc' || 'not detected' }}´
```

I know others have mentioned these issues in the release-please repo:
- https://github.com/googleapis/release-please-action/issues/962

**Comment by Aaron-Ritter** [comment]
Hi @ddennis,

Thanks a lot for the input, I have not tried it yet for monorepos. The flow should be as follows:

- The Pre-Release PR (rc-release) is created if there is a new commit which matches the change-log sections. It will take the version of the `prerelease-manifest.json` and calculate from there the new rc number. The PR file changes contain the version changes everywhere the release-type and your config are changing it, including the `prerelease-manifest.json` (since this is related to the prerelease-config.json).
- Once this PR is merged, it will create the release PR based on the commits and the `release-manifest.json`. The PR then contains the new version in all the places where the version should be updated and the `release-manifest.json` but with the  addition of `prerelease-mainfest.json`. (This is what keeps the versions in sync, the prerelease manifest needs to be set to the same as release when the release is merged/created)
- If a new commit is added at that point, it will discard the release PR it will go back to the prerelease PR.
- if the release PR is merged, the next commit will create a new prerelease PR.

From what I can see, your release PR is not updating the prerelease-manifest.json https://github.com/ddennis/release-please-prerelease-example/pull/73/files compared to my example https://github.com/sonderformat-llc/release-please-prerelease-example/pull/86/files where it updates both manifests.

You are correct that you could solve this with the manual update. However, this is problematic for protected branches. You will need a "technical" user token with elevated permissions to run this action, where the extra-files-config in the `release-config.json` does not require any additional permissions.

From what I can tell is that your match for extra files does not match, since the release PR does not contain an update. in particular the jsonpath https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-json-files.

I assume you could write `$.frontend`, my example is a bit special because of the `.`.

```
         {
          "type": "json",
          "path": "..\\/.github/prerelease-manifest.json",          
          "jsonpath": "$[\"frontend\"]"
        },   
```

This is the main cause for all the version inconsistencies and falsely created PRs.

On a side note you are using ` "release-type": "simple"` with a node project where release-please supports node.

Maybe start with generating a simple release-please config for your node-project and then extend it to the pre-release concept?

**Comment by ddennis** [comment]
Thanks @Aaron-Ritter - your feedback is appreciated.

I will need to explore. I did try using the **node* release-type in an other project but had the same issues.

Thanks .

**Comment by Aaron-Ritter** [comment]
@ddennis let me know how it goes. To summarize, make sure the `release-manifest.json` and `prerelese-manifest.json` is updated in the release PR if this is not the case, the whole workflow will break.

**Comment by Aaron-Ritter** [comment]
@ddennis I was working on a multi path project, the problem is that when using paths the workflow has to use the path output and not the general output.

```
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
```

vs.

```
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.<path>--tag_name }}
```

Which means that either for each path an own release workflow is created or maybe a matrix workflow for each path.

But for now i don't see an option how it could easily work with one manifest and config combining all paths.

**Comment by ddennis** [comment]
Thanks @Aaron-Ritter for keep sharing, really appreciate it 

I will come back to this in a week or two.

**Comment by arieluchka** [comment]
hey :)
was kinda having a similar issue as @ddennis 

First of all, thank you @Aaron-Ritter!
This repo helped me astronomically! I was so happy when i stumbled upon a link to it randomly [in this issue](https://github.com/googleapis/release-please-action/issues/1101), really made my day!

<br>
<br>

### regarding your discussion here :)

**first of all**, @Aaron-Ritter you separated all the parts of your workflow into separate jobs.
In github actions, github will spin up a separate VM for each job, **[and calculate the runtime separately](https://docs.github.com/en/billing/reference/actions-runner-pricing#:~:text=GitHub%20rounds%20the%20minutes%20and%20partial%20minutes%20each%20job%20uses%20up%20to%20the%20nearest%20whole%20minute.)**, which is slower and pricier. (if a job ran for 10 seconds, github still counts it as a whole minute)

That means that in most of your runs ([exmaple](https://github.com/sonderformat-llc/release-please-prerelease-example/actions/runs/20199586546)), if you combine everything into a single job, you can reduce the "cost" by 75% (from 4 "github" minutes to 1)
(even tho your workflow run is fast and probably under the 2000 mins-per-month free tier, i think it's still important to know the platform fuckeries)

<br>

**second thing,** is that if everything is under the same job, it's easier to work with step outputs, and no need to explicitly export them out (the whole `${{ steps.release.outputs.<path>--tag_name }}` shenanigans.).
<br>

You can check my ai-generated slop POC under the `prerelease-parse-tag` step.



<details>
<summary>Here is an example of how i wrote it</summary>

```yaml
name: CI Preflight

on:
  workflow_call:


jobs:
  preflight:
    name: Preflight Checks
    runs-on: ubuntu-latest

    steps:
      - name: Update PR with Jira reference
        uses: ORG/REPO/cicd/release/release-please-jira-override@new-release-poc
        with:
          token: ${{ secrets.token || secrets.GITHUB_TOKEN }}
          commit-sha: ${{ github.sha }}
          jira-url: 'https://ORG.atlassian.net/'

      - name: Create Prerelease Pull Request
        uses: googleapis/release-please-action@v4
        id: prerelease-prep
        with:
          config-file: ".github/release_please/prerelease-config.json"
          manifest-file: ".github/release_please/prerelease-manifest.json"
          target-branch: ${{ github.ref_name }}

      - name: Parse PreRelease Tag
        id: prerelease-parse-tag
        if: ${{ steps.prerelease-prep.outputs.releases_created == 'true' }}
        run: |
          # Get all outputs from prerelease-prep step
          OUTPUTS='${{ toJSON(steps.prerelease-prep.outputs) }}'
          echo "All outputs: $OUTPUTS"
          
          # Find the tag_name output (format: <path>--tag_name)
          TAG_NAME=$(echo "$OUTPUTS" | jq -r 'to_entries[] | select(.key | endswith("--tag_name")) | .value' | head -n 1)
          
          if [ -z "$TAG_NAME" ]; then
            echo "No tag found in outputs"
            echo "is_rc=false" >> $GITHUB_OUTPUT
            echo "tag_name=" >> $GITHUB_OUTPUT
          else
            echo "Found tag: $TAG_NAME"
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            
            # Check if it's an RC tag (contains -rc, -alpha, -beta, or similar prerelease identifiers)
            if echo "$TAG_NAME" | grep -qE '(-rc|-alpha|-beta|-pre)'; then
              echo "This is a release candidate/prerelease tag"
              echo "is_rc=true" >> $GITHUB_OUTPUT
            else
              echo "This is a stable release tag"
              echo "is_rc=false" >> $GITHUB_OUTPUT
            fi
          fi


      - name: Promote Pre-Release to QA
        if: ${{ steps.prerelease-prep.outputs.releases_created == 'true' && steps.prerelease-parse-tag.outputs.is_rc == 'true' }} 
        run: |
          echo Promote prerelease to QA

      - name: Create Release Pull Request
        uses: googleapis/release-please-action@v4
        id: release-prep
        if: ${{ steps.prerelease-prep.outputs.releases_created == 'true' && steps.prerelease-parse-tag.outputs.is_rc == 'true'}}
        with:
          config-file: ".github/release_please/release-config.json"
          manifest-file: ".github/release_please/release-manifest.json"
          target-branch: ${{ github.ref_name }}

      - name: Parse Release Tag
        id: parse-tag
        if: ${{ steps.release-prep.outputs.releases_created == 'true' }}
        run: |
          # Get all outputs from release-prep step
          OUTPUTS='${{ toJSON(steps.release-prep.outputs) }}'
          echo "All outputs: $OUTPUTS"
          
          # Find the tag_name output (format: <path>--tag_name)
          TAG_NAME=$(echo "$OUTPUTS" | jq -r 'to_entries[] | select(.key | endswith("--tag_name")) | .value' | head -n 1)
          
          if [ -z "$TAG_NAME" ]; then
            echo "No tag found in outputs"
            echo "is_rc=false" >> $GITHUB_OUTPUT
            echo "tag_name=" >> $GITHUB_OUTPUT
          else
            echo "Found tag: $TAG_NAME"
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            
            # Check if it's an RC tag (contains -rc, -alpha, -beta, or similar release identifiers)
            if echo "$TAG_NAME" | grep -qE '(-rc|-alpha|-beta|-pre)'; then
              echo "This is a release candidate/release tag"
              echo "is_rc=true" >> $GITHUB_OUTPUT
            else
              echo "This is a stable release tag"
              echo "is_rc=false" >> $GITHUB_OUTPUT
            fi
          fi
          
      - name: Promote Release to QA
        if: ${{ steps.release-prep.outputs.releases_created == 'true' && steps.prerelease-parse-tag.outputs.is_rc == 'false'}}
        run: |
          echo Promote release to QA
```

</details>

<br>

Im still figuring some things out (facing some issues when i have multiple RC prs open), but thought ill share my findings.

**Comment by Aaron-Ritter** [comment]
Hey @arieluchka, great to hear :) !

You are right about the potential time / cost savings. All thought in this particular example it is a template to add things on top, e.g. `name: Run Prerelease Tests` is used to run whatever tests relevant for your release, and there are certain benefits of having that step completely separated from other steps. In addition, it allows you to re-run certain parts individually.

And yes, you're right, the use of the outputs is a bit painful, and a single job would make it definitely easier.

**Comment by arieluchka** [comment]
Thanks for the haste response :)

Im still having an issue with trying to set this up in a mono-repo, maybe you`ll have an idea for a better approach?

Lets say i have 3 packages/components that i want to use release please with, and they all had changes and have pending pre-release prs

```
component_1 - chore(dev): release component_1 1.1.12-rc
component_2 - chore(dev): release component_2 1.2.1-rc
component_3 - chore(dev): release component_3 1.3.2-rc
```

if i merge one of these prs (`component_3` for example) , the `release-prep` step/job runs.

```
      - name: Create Release Pull Request
        uses: googleapis/release-please-action@v4
        id: release-prep
        if: ${{ steps.prerelease-prep.outputs.releases_created == 'true' && steps.prerelease-parse-tag.outputs.is_rc == 'true'}}
        with:
          config-file: ".github/release_please/release-config.json"
          manifest-file: ".github/release_please/release-manifest.json"
          target-branch: ${{ github.ref_name }}
```


but it runs on all of the components, so when there are open prs for `rc`, it will change it to a regular version

```
component_1 - chore(dev): release component_1 1.1.12
component_2 - chore(dev): release component_2 1.2.1
component_3 - chore(dev): release component_3 1.3.2
```

The next time i will run the `prerelease-prep`, it will fix it self to be

```
component_1 - chore(dev): release component_1 1.1.12-rc
component_2 - chore(dev): release component_2 1.2.1-rc
component_3 - chore(dev): release component_3 1.3.2
```


Wanted to hear if you have any idea on how to solve it, to have the `release-prep` only modify the released rc, instead of the existing prs?
maybe some way to have it only create new prs, but not modify existing ones?
